site_name: Anchorless Tech Test Docs
site_url: https://your-github-username.github.io/anchorless-tech-test/
docs_dir: .
repo_url: https://github.com/your-github-username/anchorless-tech-test
repo_name: anchorless-tech-test
nav:
  - Home: context.md
  - Multipart Upload: multipard-upload-direct-to-file-storage.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mermaid
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-github-username/anchorless-tech-test
plugins:
  - search
  - mkdocs-material
  - mkdocs-mermaid2-plugin
