site_name: Anchorless Tech Test Documentation
site_url: https://omar-karray.github.io/anchorless-tech-test/
theme:
  name: material
nav:
  - Home: index.md
  - Requirements: anchorless-test-requirements.md
  - Context: context.md
  - Data Model: data-model.md
  - Multipart Upload Flow: multipard-upload-direct-to-file-storage.md
  - API Documentation: api-docs.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.markdownextradata
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.mermaid
